#!/usr/bin/python

license = '''
The MIT License (MIT)
Copyright (c) 2014 Mats Liljegren
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
'''

import logging
import logging.handlers
import os
import sys
import argparse
import textwrap
from configobj import ConfigObj, flatten_errors
from validate import Validator, VdtValueError

""" Local imports """
from lib import loglib
from lib import config

def add_arguments(parser):
    parser.add_argument('--version', action='version', version='%(prog)s {}\n{}'.format(__version__, license))

def main():
    global log

    parser = argparse.ArgumentParser(
            formatter_class=argparse.RawDescriptionHelpFormatter,
            description=
            textwrap.dedent('''Scan mails for patches to be reviewed.
            '''))
    add_arguments(parser)
    loglib.add_arguments(parser)
    config.add_arguments(parser)
    arg = parser.parse_args()
    log = loglib.configure(arg)
    cfg = config.read(arg)

    print cfg

if __name__ == "__main__":
    try:
        from lib.version import __version__
        main()
    except KeyboardInterrupt:
        log.error('--- Keyboard interrupt received, aborting ---')
        sys.exit(1)

